[server]
maxUploadSize = 5

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
